from __future__ import annotations

from typing import Any, Protocol

from processing.models import PipelineNotice, TelegramDeliveryState


class Repository(Protocol):
    def list_sources(self) -> list[dict]: ...
    def get_by_discovery_url(self, url: str) -> Any | None: ...
    def upsert_discovered(self, notice: PipelineNotice, source_domain: str = "") -> int: ...
    def save_verification(self, notice: PipelineNotice) -> int: ...
    def enqueue_review(self, notice_id: int, reason: str) -> int: ...
    def review_candidates(self) -> list[dict]: ...
    def source_check_due(self, source_name: str, min_interval_minutes: int) -> bool: ...
    def record_source_check(self, source_name: str, source_url: str, status: str, detail: str = "") -> None: ...
    def increment_usage(self, provider: str, operation: str) -> int: ...
    def get_usage(self, provider: str, operation: str) -> int: ...
    def record_telegram_delivery(
        self, notice_id: int, channel_id: str, state: TelegramDeliveryState,
        photo_id: str | None = None, text_id: str | None = None, error: str | None = None,
    ) -> None: ...
    def start_pipeline_run(self, dry_run: bool) -> int: ...
    def finish_pipeline_run(self, run_id: int, stats: dict[str, object], state: str = "COMPLETED") -> None: ...
    def mark_digest_ready(self, notice_id: int) -> None: ...
