import {useEffect,useMemo,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {NoticeCard} from '../components/NoticeCard'
import {EMPTY_FILTERS,Filters} from '../components/Filters'
import {filterNotices} from '../lib/notices'
import {configured,supabase} from '../lib/supabase'
import type {Filters as FilterType,Notice} from '../types'

export function useNotices(){const [notices,setNotices]=useState<Notice[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{void supabase.from('notices').select('*').order('posted_at',{ascending:false}).then(({data})=>{setNotices((data||[]) as Notice[]);setLoading(false)})},[]);return {notices,loading}}
export function NoticesPage({home=false,category}:{home?:boolean;category?:string}){const {notices,loading}=useNotices();const [filters,setFilters]=useState<FilterType>({...EMPTY_FILTERS,category:category||''});const visible=useMemo(()=>filterNotices(notices,filters),[notices,filters]);return <><section className="hero"><p>অফিসিয়াল উৎস • প্রমাণভিত্তিক যাচাই • বাংলা তথ্য</p><h1>{home?'পশ্চিমবঙ্গবাসীর সরকারি তথ্যকেন্দ্র':'সমস্ত যাচাইকৃত তথ্য'}</h1>{home&&<p>চাকরি, ভর্তি, স্কলারশিপ, পরীক্ষা, প্রকল্প ও সরকারি পরিষেবার দরকারি আপডেট।</p>}</section><Filters value={filters} onChange={setFilters}/>{!configured&&<p className="warning">সাইটের Supabase public variables এখনও কনফিগার করা হয়নি।</p>}{loading?<p role="status">তথ্য লোড হচ্ছে…</p>:<section className="grid" aria-live="polite">{visible.slice(0,home?9:100).map(n=><NoticeCard key={n.id} notice={n}/>)}{!visible.length&&<p>এই ফিল্টারে কোনো প্রকাশিত তথ্য নেই।</p>}</section>}</>}
export function CategoryPage(){const {category}=useParams();return <NoticesPage category={category?.toUpperCase()}/>}
export function DetailPage(){const {id}=useParams();const [notice,setNotice]=useState<Notice|null>(null);const [revisions,setRevisions]=useState<Record<string,unknown>[]>([]);useEffect(()=>{void(async()=>{const {data}=await supabase.from('notices').select('*').eq('id',id).single();setNotice(data as Notice);const result=await supabase.from('notice_revisions').select('*').eq('notice_id',id).order('revision_number',{ascending:false});setRevisions(result.data||[])})()},[id]);useEffect(()=>{if(!notice)return;const title=notice.title_bn||notice.original_title;document.title=`${title} — সরকারি তথ্যকেন্দ্র`;const meta=document.querySelector('meta[name="description"]');meta?.setAttribute('content',`${title}। অফিসিয়াল উৎস যাচাই: ${notice.verified_at||'দেখুন'}`);return()=>{document.title='সরকারি তথ্যকেন্দ্র'}},[notice]);if(!notice)return <p role="status">তথ্য লোড হচ্ছে…</p>;const url=notice.official_document_url||notice.official_page_url||notice.final_resolved_url;const share=encodeURIComponent(`${notice.title_bn||notice.original_title} ${location.href}`);return <article className="detail"><div className="badges"><span>{notice.category}</span><span>{notice.subtype}</span></div><h1>{notice.title_bn||notice.original_title}</h1><p>{notice.relevance_reason}</p><dl><div><dt>প্রকাশকারী</dt><dd>{notice.issuing_authority||'—'}</dd></div><div><dt>শেষ তারিখ</dt><dd>{notice.original_deadline_text||notice.deadline||'—'}</dd></div><div><dt>আবেদনযোগ্যতা</dt><dd>{notice.eligibility_status||'অফিসিয়াল নোটিশ দেখুন'}</dd></div><div><dt>সর্বশেষ যাচাই</dt><dd>{notice.verified_at?new Date(notice.verified_at).toLocaleString('bn-IN'):'—'}</dd></div></dl>{url&&<a className="button" href={url} target="_blank" rel="noopener noreferrer">অফিসিয়াল নোটিশ খুলুন</a>}<p className="shares"><a href={`https://t.me/share/url?url=${share}`}>Telegram-এ শেয়ার</a> <a href={`https://wa.me/?text=${share}`}>WhatsApp-এ শেয়ার</a></p><h2>সংশোধন ও সংস্করণ</h2>{revisions.length?<ol>{revisions.map((r,i)=><li key={i}>সংস্করণ {String(r.revision_number)} — {new Date(String(r.detected_at)).toLocaleDateString('bn-IN')}</li>)}</ol>:<p>কোনো সংশোধন নথিভুক্ত নেই।</p>}</article>}
export function DeadlinePage(){const {notices}=useNotices();const filters={...EMPTY_FILTERS,sort:'deadline' as const};return <><h1>শেষ তারিখ</h1><section className="grid">{filterNotices(notices,filters).map(n=><NoticeCard key={n.id} notice={n}/>)}</section></>}
export function StaticPage({kind}:{kind:string}){const pages:Record<string,[string,string]>= {about:['আমাদের সম্পর্কে','সরকারি তথ্যকেন্দ্র পশ্চিমবঙ্গবাসীর জন্য দরকারি সরকারি তথ্য অফিসিয়াল উৎস থেকে যাচাই করে বাংলায় সাজায়।'],policy:['যাচাই নীতি','কোনো aggregator-কে প্রমাণ ধরা হয় না। অফিসিয়াল URL, ডোমেইন, নথি, ক্ষেত্রভিত্তিক প্রমাণ, যোগ্যতা এবং সময়সীমা যাচাই না হলে তথ্য প্রকাশিত হয় না।'],disclaimer:['দায়মুক্তি','এই সাইট সরকারি দপ্তর নয়। আবেদন বা সিদ্ধান্ত নেওয়ার আগে লিঙ্ক করা অফিসিয়াল নোটিশ অবশ্যই পড়ুন।'],privacy:['গোপনীয়তা','পাবলিক সাইটে কোনো অপ্রয়োজনীয় ব্যক্তিগত তথ্য সংগ্রহ করা হয় না। Supabase Auth শুধু প্রশাসনিক প্রবেশের জন্য ব্যবহৃত হয়।'],telegram:['Telegram','তাৎক্ষণিক উচ্চ-গুরুত্বের আপডেট পেতে কনফিগার করা Telegram চ্যানেলে যোগ দিন।']};const [title,body]=pages[kind];return <article className="static"><h1>{title}</h1><p>{body}</p>{kind==='telegram'&&import.meta.env.VITE_TELEGRAM_CHANNEL_URL&&<a className="button" href={import.meta.env.VITE_TELEGRAM_CHANNEL_URL}>চ্যানেল খুলুন</a>}<p><Link to="/">হোমে ফিরুন</Link></p></article>}
