-- Bengali Government Information Platform: normalized production schema.
-- Run in Supabase SQL Editor as the project owner. Safe to run repeatedly.
create extension if not exists pgcrypto;

create table if not exists public.sources (
  id bigint generated by default as identity primary key,
  name text not null, slug text not null unique, source_type text not null
    check (source_type in ('RSS','HTML','JSON_API','OFFICIAL_PDF_LIST','SITEMAP','MANUAL')),
  parser_type text not null, base_url text not null, feed_url text,
  official boolean not null default false, discovery_only boolean not null default true,
  enabled boolean not null default false, categories text[] not null default '{}', state text,
  authority_type text, allowed_domains text[] not null default '{}',
  allowed_document_domains text[] not null default '{}', item_selector text, title_selector text,
  link_selector text, summary_selector text, date_selector text,
  min_interval_minutes integer not null default 120 check (min_interval_minutes >= 0),
  request_timeout integer not null default 20 check (request_timeout between 1 and 60),
  max_items integer not null default 20 check (max_items between 1 and 100),
  robots_status text, terms_reviewed boolean not null default false, selector_verified_at timestamptz,
  last_success_at timestamptz, last_failure_at timestamptz,
  consecutive_failures integer not null default 0, health_status text not null default 'UNKNOWN',
  notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check (not enabled or source_type in ('RSS','JSON_API','SITEMAP','MANUAL')
         or (item_selector is not null and title_selector is not null and link_selector is not null))
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  category text not null, subtype text not null default 'NEW', original_title text not null,
  title_bn text, title_en text, issuing_authority text, discovery_source_id bigint references public.sources(id),
  discovery_url text not null unique, source_name text, source_domain text, discovery_summary text,
  candidate_official_links jsonb not null default '[]', source_official boolean not null default false,
  discovery_only boolean not null default true, official_page_url text, official_document_url text,
  final_resolved_url text, canonical_official_url text, official_domain text,
  official_document_hash text, notice_number text, notice_date text, published_date text, deadline date,
  original_deadline_text text, deadline_state text not null default 'UNKNOWN'
    check (deadline_state in ('OPEN','CLOSING_SOON','EXPIRED','CANCELLED','UNKNOWN')),
  eligibility_status text, west_bengal_relevance text not null default 'LOW'
    check (west_bengal_relevance in ('HIGH','MEDIUM','LOW','REJECT')),
  relevance_reason text, publication_priority text not null default 'NORMAL'
    check (publication_priority in ('URGENT','HIGH','NORMAL','DIGEST_ONLY','REJECT')),
  publication_status text not null default 'DRAFT'
    check (publication_status in ('DRAFT','REVIEW','APPROVED','PUBLISHED','REJECTED')),
  verification_score integer not null default 0 check (verification_score between 0 and 100),
  verification_status text not null default 'DISCOVERED', structured_data jsonb,
  conflict_reason text, render_status text, revision_number integer not null default 1,
  manually_approved boolean not null default false, manual_override_reason text,
  first_seen_at timestamptz not null default now(), last_checked_at timestamptz not null default now(),
  verified_at timestamptz, posted_at timestamptz, created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists notices_official_revision_unique
  on public.notices(canonical_official_url, official_document_hash)
  where canonical_official_url is not null and official_document_hash is not null;
create index if not exists notices_category_status_idx on public.notices(category, publication_status);
create index if not exists notices_deadline_idx on public.notices(deadline, deadline_state);
create index if not exists notices_relevance_idx on public.notices(west_bengal_relevance);
create index if not exists notices_canonical_url_idx on public.notices(canonical_official_url);

create table if not exists public.notice_revisions (
  id bigint generated by default as identity primary key, notice_id bigint not null references public.notices(id) on delete cascade,
  revision_number integer not null, official_document_hash text not null, official_url text,
  subtype text not null default 'UPDATED', structured_data jsonb, change_summary text,
  detected_at timestamptz not null default now(), unique(notice_id, revision_number)
);
create index if not exists notice_revisions_notice_idx on public.notice_revisions(notice_id, detected_at desc);

create table if not exists public.notice_evidence (
  id bigint generated by default as identity primary key, notice_id bigint not null references public.notices(id) on delete cascade,
  field_name text not null, extracted_value jsonb, evidence_text text, page_number integer check (page_number > 0),
  source_url text not null, validation_status text not null default 'PENDING', created_at timestamptz not null default now()
);
create index if not exists notice_evidence_notice_idx on public.notice_evidence(notice_id, field_name);

create table if not exists public.review_queue (
  id bigint generated by default as identity primary key, notice_id bigint not null references public.notices(id) on delete cascade,
  review_reason text not null, status text not null default 'PENDING', priority text not null default 'NORMAL',
  admin_note text, corrected_official_url text, corrected_structured_data jsonb,
  assigned_reviewer uuid references auth.users(id), override_reason text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), resolved_at timestamptz
);
create unique index if not exists review_queue_one_active_idx on public.review_queue(notice_id)
  where status in ('PENDING','APPROVED','RETRY','PROCESSING');

create table if not exists public.source_checks (
  id bigint generated by default as identity primary key, source_id bigint references public.sources(id),
  source_name text not null, source_url text not null, status text not null, detail text,
  response_ms integer, items_found integer not null default 0, checked_at timestamptz not null default now()
);
alter table public.source_checks add column if not exists legacy_import_key text;
create unique index if not exists source_checks_legacy_import_key_idx
  on public.source_checks(legacy_import_key);
create index if not exists source_checks_due_idx on public.source_checks(source_name, checked_at desc);

create table if not exists public.pipeline_runs (
  id bigint generated by default as identity primary key, started_at timestamptz not null default now(), ended_at timestamptz,
  state text not null default 'RUNNING', sources_checked integer not null default 0,
  items_discovered integer not null default 0, items_verified integer not null default 0,
  items_posted integer not null default 0, items_rejected integer not null default 0,
  items_queued integer not null default 0, duplicates integer not null default 0,
  errors jsonb not null default '[]', dry_run boolean not null default false
);

create table if not exists public.provider_usage (
  provider text not null, usage_date date not null default current_date, operation text not null,
  calls integer not null default 0, primary key(provider, usage_date, operation)
);

create table if not exists public.telegram_posts (
  id bigint generated by default as identity primary key, notice_id bigint not null references public.notices(id) on delete cascade,
  channel_id text not null, photo_message_id text, text_message_id text,
  delivery_state text not null default 'NOT_SENT'
    check (delivery_state in ('NOT_SENT','PHOTO_SENT','TEXT_SENT','FULLY_SENT','PARTIAL_FAILURE','FAILED')),
  error text, retry_count integer not null default 0, created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(), unique(notice_id, channel_id)
);

create table if not exists public.publication_digests (
  id bigint generated by default as identity primary key, digest_date date not null unique,
  notice_ids bigint[] not null default '{}', telegram_message_id text,
  delivery_state text not null default 'NOT_SENT', error text,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade, email text,
  role text not null default 'viewer' check (role in ('viewer','reviewer','admin')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  categories text[] not null default '{}', relevance text[] not null default '{}', district text,
  telegram_chat_id text, enabled boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key, actor_id uuid references auth.users(id),
  action text not null, entity_type text not null, entity_id text not null, reason text not null,
  changes jsonb not null default '{}', created_at timestamptz not null default now()
);

create or replace function public.is_admin() returns boolean language sql stable security definer
set search_path = public as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role in ('admin','reviewer'));
$$;

create or replace function public.increment_provider_usage(p_provider text, p_operation text)
returns integer language plpgsql security definer set search_path = public as $$
declare result integer;
begin
  insert into public.provider_usage(provider, usage_date, operation, calls)
  values (p_provider, current_date, p_operation, 1)
  on conflict(provider, usage_date, operation) do update set calls=provider_usage.calls+1
  returning calls into result;
  return result;
end $$;
revoke all on function public.increment_provider_usage(text,text) from public, anon, authenticated;
grant execute on function public.increment_provider_usage(text,text) to service_role;

alter table public.sources enable row level security;
alter table public.notices enable row level security;
alter table public.notice_revisions enable row level security;
alter table public.notice_evidence enable row level security;
alter table public.review_queue enable row level security;
alter table public.source_checks enable row level security;
alter table public.pipeline_runs enable row level security;
alter table public.provider_usage enable row level security;
alter table public.telegram_posts enable row level security;
alter table public.publication_digests enable row level security;
alter table public.profiles enable row level security;
alter table public.user_preferences enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "public published notices" on public.notices;
create policy "public published notices" on public.notices for select to anon, authenticated
  using (publication_status='PUBLISHED' and verification_status in ('VERIFIED_OFFICIAL','POSTED'));
drop policy if exists "public published revisions" on public.notice_revisions;
create policy "public published revisions" on public.notice_revisions for select to anon, authenticated
  using (exists(select 1 from public.notices n where n.id=notice_id and n.publication_status='PUBLISHED'
               and n.verification_status in ('VERIFIED_OFFICIAL','POSTED')));
drop policy if exists "public published evidence" on public.notice_evidence;
create policy "public published evidence" on public.notice_evidence for select to anon, authenticated
  using (validation_status='VALID' and exists(select 1 from public.notices n where n.id=notice_id
         and n.publication_status='PUBLISHED' and n.verification_status in ('VERIFIED_OFFICIAL','POSTED')));

drop policy if exists "admins manage sources" on public.sources;
create policy "admins manage sources" on public.sources for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins manage notices" on public.notices;
create policy "admins manage notices" on public.notices for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins manage revisions" on public.notice_revisions;
create policy "admins manage revisions" on public.notice_revisions for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins manage evidence" on public.notice_evidence;
create policy "admins manage evidence" on public.notice_evidence for all to authenticated using (public.is_admin()) with check (public.is_admin());

do $$ declare table_name text; begin
  foreach table_name in array array['review_queue','source_checks','pipeline_runs','provider_usage','telegram_posts','publication_digests','audit_logs'] loop
    execute format('drop policy if exists "admins only %s" on public.%I', table_name, table_name);
    execute format('create policy "admins only %s" on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())', table_name, table_name);
  end loop;
end $$;
drop policy if exists "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles for select to authenticated using (id=auth.uid() or public.is_admin());
drop policy if exists "users own preferences" on public.user_preferences;
create policy "users own preferences" on public.user_preferences for all to authenticated
  using (user_id=auth.uid() or public.is_admin()) with check (user_id=auth.uid() or public.is_admin());

-- Service-role requests used by GitHub Actions bypass RLS. Never use that key in Vite.
